In [2]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('../bases_dados/credit_data.csv')

In [8]:
df.head()

i#clientid        income        age         loan  c#default
0           1  66155.925095  59.017015  8106.532131          0
1           2  34415.153966  48.117153  6564.745018          0
2           3  57317.170063  63.108049  8020.953296          0
3           4  42709.534201  45.751972  6103.642260          0
4           5  66952.688845  18.584336  8770.099235          1

In [9]:
df.isnull().sum()

i#clientid    0
income        0
age           3
loan          0
c#default     0
dtype: int64

In [10]:
df.dropna(inplace=True)

## Sem pradronização

In [12]:
x = df.iloc[:, 1:4].values
x

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [13]:
y = df.iloc[:, 4].values
y

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [14]:
x.shape, y.shape

((1997, 3), (1997,))

In [15]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [18]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.2, stratify=y)

In [30]:
np.mean(x_treino[0]), np.median(x_treino[0]), np.std(x_treino[0])

(11206.517607414784, 4948.488069855121, 12468.507693526144)

In [32]:
np.mean(x_teste[0]), np.median(x_teste[0]), np.std(x_teste[0])

(7207.980545028357, 758.43484908373, 9617.769686263064)

In [19]:
knn = KNeighborsClassifier()

In [26]:
knn.fit(x_treino, y_treino)

KNeighborsClassifier()

In [27]:
previsoes = knn.predict(x_teste)

In [28]:
previsoes

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,

In [29]:
y_teste

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,

In [31]:
accuracy_score(y_teste, previsoes)

0.8225

## Com padronização

In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
z_treino = StandardScaler() # z-score treino

In [35]:
z_teste = StandardScaler() # z-score teste

In [36]:
x_treinamento = z_treino.fit_transform(x_treino)

In [37]:
x_teste = z_treino.fit_transform(x_teste)

In [38]:
x_treinamento, x_teste

(array([[-1.18084587,  1.29955108,  0.1640231 ],
        [-0.07626434, -0.94760008,  0.52242364],
        [ 0.70009613, -1.13045996,  1.91059254],
        ...,
        [ 0.3485018 , -1.22798916,  0.55000415],
        [ 0.31020879, -0.84382577,  0.95165314],
        [-1.021331  , -0.14695921, -0.12135079]]),
 array([[-1.64261895,  1.67144404, -1.22108532],
        [-1.34172971, -1.56104495, -1.13175385],
        [ 1.64390558,  0.33853584,  3.09628396],
        ...,
        [-0.37495982, -0.50006183, -0.61286086],
        [ 0.90754396,  1.72899452, -0.08948437],
        [-0.69554422, -1.11932825, -0.52608489]]))

In [39]:
min(x_treinamento[0]), max(x_treinamento[0]) # menor e maior renda padronizados

(-1.1808458688022656, 1.2995510776891952)

In [40]:
np.mean(x_treinamento[0]), np.median(x_treinamento[0]), np.std(x_treinamento[0])

(0.09424276850242132, 0.16402309662033437, 1.0138192553196135)

In [42]:
np.mean(x_treinamento), np.median(x_treinamento), np.std(x_treinamento)

(-1.5201550911168915e-15, -0.035913655645948665, 0.9999999999999998)

In [43]:
np.mean(x_teste), np.median(x_teste), np.std(x_teste)

(-2.7385501274087196e-16, -0.02447224003499049, 1.0000000000000002)

In [45]:
knn.fit(x_treinamento, y_treino)

KNeighborsClassifier()

In [46]:
previsoes = knn.predict(x_teste)

In [48]:
accuracy_score(previsoes, y_teste) * 100

97.75